version: "3.8"

services:
  redis:
    image: redis:7
    container_name: desafio-redis
    ports:
      - "6379:6379"
    restart: always


  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: desafio-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend/firebase-key.json:/app/firebase-key.json


  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: desafio-worker
    depends_on:
      - redis
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend/firebase-key.json:/app/firebase-key.json


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: desafio-frontend
    ports:
      - "5173:80"
    depends_on:
      - api
